[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 100_000_000
fuzz.runs = 10_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[fmt]
sort_imports = true
bracket_spacing = true
single_line_statement_blocks = "single"
multiline_func_header = "params_first"
wrap_comments = true
tab_width = 4
