[profile.default]
src = "contracts"
test = "contracts/test"
script = "script"
libs = ["lib"]

evm_version = "cancun" 
solc_version = "0.8.23"
optimizer_runs = 1000
bytecode_hash = "none"
ffi=true

block_base_fee_per_gas = 100000000 
block_number = 120000 
block_timestamp = 1640000000 
fs_permissions = [{access = "read-write", path = "./"}] 
gas_limit = 9223372036854775807

[fuzz]
max_test_rejects = 1000000
runs = 256
