[profile.default]
# Directory Setup
script = "script"
src = "contracts"
test = "test"

# Gas/Memory
gas_limit = '18446744073709551615' 
memory_limit = 1073741824 # 1 GB

# Compiler Options
bytecode_hash = "none"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.28"
via_ir = false

# Permissions
fs_permissions = [{access = "read-write", path = "./"}]

[rpc_endpoints]
base = "https://base-mainnet.infura.io/v3/b6bf7d3508c941499b10025c0776eaf8"
mainnet = "https://mainnet.infura.io/v3/b6bf7d3508c941499b10025c0776eaf8"

[etherscan]
base = {url = "https://api.basescan.org/api", key = "${ETHERSCAN_API_KEY_8453}"}
mainnet = {url = "https://api.etherscan.io/api", key = "${ETHERSCAN_API_KEY_1}"}
